/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PathLessLayoutRouteImport } from './routes/_pathLessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PathLessLayoutDashRouteImport } from './routes/_pathLessLayout.Dash'
import { Route as PathLessLayoutAddWorkKanbanRouteImport } from './routes/_pathLessLayout.AddWorkKanban'

const PathLessLayoutRoute = PathLessLayoutRouteImport.update({
  id: '/_pathLessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathLessLayoutDashRoute = PathLessLayoutDashRouteImport.update({
  id: '/Dash',
  path: '/Dash',
  getParentRoute: () => PathLessLayoutRoute,
} as any)
const PathLessLayoutAddWorkKanbanRoute =
  PathLessLayoutAddWorkKanbanRouteImport.update({
    id: '/AddWorkKanban',
    path: '/AddWorkKanban',
    getParentRoute: () => PathLessLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/AddWorkKanban': typeof PathLessLayoutAddWorkKanbanRoute
  '/Dash': typeof PathLessLayoutDashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/AddWorkKanban': typeof PathLessLayoutAddWorkKanbanRoute
  '/Dash': typeof PathLessLayoutDashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathLessLayout': typeof PathLessLayoutRouteWithChildren
  '/_pathLessLayout/AddWorkKanban': typeof PathLessLayoutAddWorkKanbanRoute
  '/_pathLessLayout/Dash': typeof PathLessLayoutDashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/AddWorkKanban' | '/Dash'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/AddWorkKanban' | '/Dash'
  id:
    | '__root__'
    | '/'
    | '/_pathLessLayout'
    | '/_pathLessLayout/AddWorkKanban'
    | '/_pathLessLayout/Dash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathLessLayoutRoute: typeof PathLessLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathLessLayout': {
      id: '/_pathLessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathLessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathLessLayout/Dash': {
      id: '/_pathLessLayout/Dash'
      path: '/Dash'
      fullPath: '/Dash'
      preLoaderRoute: typeof PathLessLayoutDashRouteImport
      parentRoute: typeof PathLessLayoutRoute
    }
    '/_pathLessLayout/AddWorkKanban': {
      id: '/_pathLessLayout/AddWorkKanban'
      path: '/AddWorkKanban'
      fullPath: '/AddWorkKanban'
      preLoaderRoute: typeof PathLessLayoutAddWorkKanbanRouteImport
      parentRoute: typeof PathLessLayoutRoute
    }
  }
}

interface PathLessLayoutRouteChildren {
  PathLessLayoutAddWorkKanbanRoute: typeof PathLessLayoutAddWorkKanbanRoute
  PathLessLayoutDashRoute: typeof PathLessLayoutDashRoute
}

const PathLessLayoutRouteChildren: PathLessLayoutRouteChildren = {
  PathLessLayoutAddWorkKanbanRoute: PathLessLayoutAddWorkKanbanRoute,
  PathLessLayoutDashRoute: PathLessLayoutDashRoute,
}

const PathLessLayoutRouteWithChildren = PathLessLayoutRoute._addFileChildren(
  PathLessLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathLessLayoutRoute: PathLessLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
